name: Sample Service Validator Config Distribution Builder
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [created]
  workflow_dispatch:
jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub Repo
        uses: actions/checkout@v2
      - name: Generate useful environment variables; recommended by GitHub.
        uses: FranzDiebold/github-env-vars-action@v2
      - name: Get current date for usage in subsequent steps as env.BUILD_DATE
        run: echo BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') >> $GITHUB_ENV
      - name: Print environment variables; helps diagnosing issues with a workflow
        run: |
          echo "CI_REPOSITORY_SLUG=$CI_REPOSITORY_SLUG"
          echo "CI_REPOSITORY_OWNER=$CI_REPOSITORY_OWNER"
          echo "CI_REPOSITORY_OWNER_SLUG=$CI_REPOSITORY_OWNER_SLUG"
          echo "CI_REPOSITORY_NAME=$CI_REPOSITORY_NAME"
          echo "CI_REPOSITORY_NAME_SLUG=$CI_REPOSITORY_NAME_SLUG"
          echo "CI_REPOSITORY=$CI_REPOSITORY"
          echo "CI_REF_SLUG=$CI_REF_SLUG"
          echo "CI_ACTION_REF_NAME=$CI_ACTION_REF_NAME"
          echo "CI_ACTION_REF_NAME_SLUG=$CI_ACTION_REF_NAME_SLUG"
          echo "CI_REF_NAME=$CI_REF_NAME"
          echo "CI_REF_NAME_SLUG=$CI_REF_NAME_SLUG"
          echo "CI_REF=$CI_REF"
          echo "CI_HEAD_REF_SLUG=$CI_HEAD_REF_SLUG"
          echo "CI_HEAD_REF=$CI_HEAD_REF"
          echo "CI_BASE_REF_SLUG=$CI_BASE_REF_SLUG"
          echo "CI_BASE_REF=$CI_BASE_REF"
          echo "CI_SHA_SHORT=$CI_SHA_SHORT"
          echo "CI_SHA=$CI_SHA"
          echo "CI_ACTOR=$CI_ACTOR"
          echo "CI_EVENT_NAME=$CI_EVENT_NAME"
          echo "CI_RUN_ID=$CI_RUN_ID"
          echo "CI_RUN_NUMBER=$CI_RUN_NUMBER"
          echo "CI_WORKFLOW=$CI_WORKFLOW"
          echo "CI_ACTION=$CI_ACTION"
          echo "BUILD_DATE=${{ env.BUILD_DATE }}"
      - name: build container
        run: docker build -t cli .
      - name: run tests in container
        run: docker run cli scripts/run_tests.sh
      - name: build UI exports in "dist" directory
        run: docker run -v `pwd`/dist:/kb/module/dist cli ui_scripts/export.sh 
      - name build validators in "dist" directory:
        run: docker run -v `pwd`/dist:/kb/module/dist cli scripts/merge_validators.sh
      - name build validators in "dist" directory:
        run: docker run -v `pwd`/dist:/kb/module/dist cli scripts/create_tsv.sh
      - name: create a branch, depending on the workflow action
        uses: s0/git-publish-subdir-action@2.5.0
        env:
          REPO: self
          BRANCH: dist-${{ env.CI_REF_NAME_SLUG }}
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

                