name: Sample Service Validator Config Build and Test
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub Repo
        uses: actions/checkout@v2

      #
      # Generate the config files
      #
      - name: Validate sources, generate configs, and verify generated configs
        run: make
