name: Sample Service Validator Config Tests
on:
  [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Github Repo
      uses: actions/checkout@v2
    - name: build container
      run: docker build -t test .
    - name: run tests in container
      run: docker run test
